language: generic

sudo: required

services:
  - docker

before_install:
  - docker -t 5hdumat/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true 5hdumat/react-test-app npm test

after_success:
  - docker build -t 5hdumat/docker-frontend ./frontend
  - docker build -t 5hdumat/docker-backend ./backend
  - docker build -t 5hdumat/nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push 5hdumat/docker-frontend
  - docker push 5hdumat/docker-backend
  - docker push 5hdumat/nginx
